# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.15.2/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.15.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fmmarques/Documentos/Projects/bejeweled

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fmmarques/Documentos/Projects/bejeweled

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/cmake-3.15.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.15.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(CMAKE_COMMAND) -E cmake_progress_start /home/fmmarques/Documentos/Projects/bejeweled/CMakeFiles /home/fmmarques/Documentos/Projects/bejeweled/dependencies/yage/CMakeFiles/progress.marks
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmmarques/Documentos/Projects/bejeweled/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
dependencies/yage/CMakeFiles/state_machine_test.dir/rule:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/CMakeFiles/state_machine_test.dir/rule
.PHONY : dependencies/yage/CMakeFiles/state_machine_test.dir/rule

# Convenience name for target.
state_machine_test: dependencies/yage/CMakeFiles/state_machine_test.dir/rule

.PHONY : state_machine_test

# fast build rule for target.
state_machine_test/fast:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/state_machine_test.dir/build.make dependencies/yage/CMakeFiles/state_machine_test.dir/build
.PHONY : state_machine_test/fast

# Convenience name for target.
dependencies/yage/CMakeFiles/yage.dir/rule:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/CMakeFiles/yage.dir/rule
.PHONY : dependencies/yage/CMakeFiles/yage.dir/rule

# Convenience name for target.
yage: dependencies/yage/CMakeFiles/yage.dir/rule

.PHONY : yage

# fast build rule for target.
yage/fast:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/build
.PHONY : yage/fast

# Convenience name for target.
dependencies/yage/CMakeFiles/all_tests.dir/rule:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/CMakeFiles/all_tests.dir/rule
.PHONY : dependencies/yage/CMakeFiles/all_tests.dir/rule

# Convenience name for target.
all_tests: dependencies/yage/CMakeFiles/all_tests.dir/rule

.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/all_tests.dir/build.make dependencies/yage/CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

# Convenience name for target.
dependencies/yage/CMakeFiles/graphics_test.dir/rule:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f CMakeFiles/Makefile2 dependencies/yage/CMakeFiles/graphics_test.dir/rule
.PHONY : dependencies/yage/CMakeFiles/graphics_test.dir/rule

# Convenience name for target.
graphics_test: dependencies/yage/CMakeFiles/graphics_test.dir/rule

.PHONY : graphics_test

# fast build rule for target.
graphics_test/fast:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/build
.PHONY : graphics_test/fast

src/engine/game_engine.o: src/engine/game_engine.cpp.o

.PHONY : src/engine/game_engine.o

# target to build an object file
src/engine/game_engine.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/game_engine.cpp.o
.PHONY : src/engine/game_engine.cpp.o

src/engine/game_engine.i: src/engine/game_engine.cpp.i

.PHONY : src/engine/game_engine.i

# target to preprocess a source file
src/engine/game_engine.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/game_engine.cpp.i
.PHONY : src/engine/game_engine.cpp.i

src/engine/game_engine.s: src/engine/game_engine.cpp.s

.PHONY : src/engine/game_engine.s

# target to generate assembly for a file
src/engine/game_engine.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/game_engine.cpp.s
.PHONY : src/engine/game_engine.cpp.s

src/engine/game_state.o: src/engine/game_state.cpp.o

.PHONY : src/engine/game_state.o

# target to build an object file
src/engine/game_state.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/game_state.cpp.o
.PHONY : src/engine/game_state.cpp.o

src/engine/game_state.i: src/engine/game_state.cpp.i

.PHONY : src/engine/game_state.i

# target to preprocess a source file
src/engine/game_state.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/game_state.cpp.i
.PHONY : src/engine/game_state.cpp.i

src/engine/game_state.s: src/engine/game_state.cpp.s

.PHONY : src/engine/game_state.s

# target to generate assembly for a file
src/engine/game_state.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/game_state.cpp.s
.PHONY : src/engine/game_state.cpp.s

src/engine/state_machine.o: src/engine/state_machine.cpp.o

.PHONY : src/engine/state_machine.o

# target to build an object file
src/engine/state_machine.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/state_machine.cpp.o
.PHONY : src/engine/state_machine.cpp.o

src/engine/state_machine.i: src/engine/state_machine.cpp.i

.PHONY : src/engine/state_machine.i

# target to preprocess a source file
src/engine/state_machine.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/state_machine.cpp.i
.PHONY : src/engine/state_machine.cpp.i

src/engine/state_machine.s: src/engine/state_machine.cpp.s

.PHONY : src/engine/state_machine.s

# target to generate assembly for a file
src/engine/state_machine.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/state_machine.cpp.s
.PHONY : src/engine/state_machine.cpp.s

src/engine/states/splash_screen.o: src/engine/states/splash_screen.cpp.o

.PHONY : src/engine/states/splash_screen.o

# target to build an object file
src/engine/states/splash_screen.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/states/splash_screen.cpp.o
.PHONY : src/engine/states/splash_screen.cpp.o

src/engine/states/splash_screen.i: src/engine/states/splash_screen.cpp.i

.PHONY : src/engine/states/splash_screen.i

# target to preprocess a source file
src/engine/states/splash_screen.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/states/splash_screen.cpp.i
.PHONY : src/engine/states/splash_screen.cpp.i

src/engine/states/splash_screen.s: src/engine/states/splash_screen.cpp.s

.PHONY : src/engine/states/splash_screen.s

# target to generate assembly for a file
src/engine/states/splash_screen.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/engine/states/splash_screen.cpp.s
.PHONY : src/engine/states/splash_screen.cpp.s

src/events/event_manager.o: src/events/event_manager.cpp.o

.PHONY : src/events/event_manager.o

# target to build an object file
src/events/event_manager.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/events/event_manager.cpp.o
.PHONY : src/events/event_manager.cpp.o

src/events/event_manager.i: src/events/event_manager.cpp.i

.PHONY : src/events/event_manager.i

# target to preprocess a source file
src/events/event_manager.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/events/event_manager.cpp.i
.PHONY : src/events/event_manager.cpp.i

src/events/event_manager.s: src/events/event_manager.cpp.s

.PHONY : src/events/event_manager.s

# target to generate assembly for a file
src/events/event_manager.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/events/event_manager.cpp.s
.PHONY : src/events/event_manager.cpp.s

src/graphics/drawable.abstract.o: src/graphics/drawable.abstract.cpp.o

.PHONY : src/graphics/drawable.abstract.o

# target to build an object file
src/graphics/drawable.abstract.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/drawable.abstract.cpp.o
.PHONY : src/graphics/drawable.abstract.cpp.o

src/graphics/drawable.abstract.i: src/graphics/drawable.abstract.cpp.i

.PHONY : src/graphics/drawable.abstract.i

# target to preprocess a source file
src/graphics/drawable.abstract.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/drawable.abstract.cpp.i
.PHONY : src/graphics/drawable.abstract.cpp.i

src/graphics/drawable.abstract.s: src/graphics/drawable.abstract.cpp.s

.PHONY : src/graphics/drawable.abstract.s

# target to generate assembly for a file
src/graphics/drawable.abstract.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/drawable.abstract.cpp.s
.PHONY : src/graphics/drawable.abstract.cpp.s

src/graphics/font.o: src/graphics/font.cpp.o

.PHONY : src/graphics/font.o

# target to build an object file
src/graphics/font.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/font.cpp.o
.PHONY : src/graphics/font.cpp.o

src/graphics/font.i: src/graphics/font.cpp.i

.PHONY : src/graphics/font.i

# target to preprocess a source file
src/graphics/font.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/font.cpp.i
.PHONY : src/graphics/font.cpp.i

src/graphics/font.s: src/graphics/font.cpp.s

.PHONY : src/graphics/font.s

# target to generate assembly for a file
src/graphics/font.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/font.cpp.s
.PHONY : src/graphics/font.cpp.s

src/graphics/font_manager.o: src/graphics/font_manager.cpp.o

.PHONY : src/graphics/font_manager.o

# target to build an object file
src/graphics/font_manager.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/font_manager.cpp.o
.PHONY : src/graphics/font_manager.cpp.o

src/graphics/font_manager.i: src/graphics/font_manager.cpp.i

.PHONY : src/graphics/font_manager.i

# target to preprocess a source file
src/graphics/font_manager.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/font_manager.cpp.i
.PHONY : src/graphics/font_manager.cpp.i

src/graphics/font_manager.s: src/graphics/font_manager.cpp.s

.PHONY : src/graphics/font_manager.s

# target to generate assembly for a file
src/graphics/font_manager.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/font_manager.cpp.s
.PHONY : src/graphics/font_manager.cpp.s

src/graphics/graphics_manager.o: src/graphics/graphics_manager.cpp.o

.PHONY : src/graphics/graphics_manager.o

# target to build an object file
src/graphics/graphics_manager.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/graphics_manager.cpp.o
.PHONY : src/graphics/graphics_manager.cpp.o

src/graphics/graphics_manager.i: src/graphics/graphics_manager.cpp.i

.PHONY : src/graphics/graphics_manager.i

# target to preprocess a source file
src/graphics/graphics_manager.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/graphics_manager.cpp.i
.PHONY : src/graphics/graphics_manager.cpp.i

src/graphics/graphics_manager.s: src/graphics/graphics_manager.cpp.s

.PHONY : src/graphics/graphics_manager.s

# target to generate assembly for a file
src/graphics/graphics_manager.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/graphics_manager.cpp.s
.PHONY : src/graphics/graphics_manager.cpp.s

src/graphics/spritesheet.o: src/graphics/spritesheet.cpp.o

.PHONY : src/graphics/spritesheet.o

# target to build an object file
src/graphics/spritesheet.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/spritesheet.cpp.o
.PHONY : src/graphics/spritesheet.cpp.o

src/graphics/spritesheet.i: src/graphics/spritesheet.cpp.i

.PHONY : src/graphics/spritesheet.i

# target to preprocess a source file
src/graphics/spritesheet.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/spritesheet.cpp.i
.PHONY : src/graphics/spritesheet.cpp.i

src/graphics/spritesheet.s: src/graphics/spritesheet.cpp.s

.PHONY : src/graphics/spritesheet.s

# target to generate assembly for a file
src/graphics/spritesheet.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/spritesheet.cpp.s
.PHONY : src/graphics/spritesheet.cpp.s

src/graphics/texture.o: src/graphics/texture.cpp.o

.PHONY : src/graphics/texture.o

# target to build an object file
src/graphics/texture.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.cpp.o

src/graphics/texture.i: src/graphics/texture.cpp.i

.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.cpp.i

src/graphics/texture.s: src/graphics/texture.cpp.s

.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.cpp.s

src/graphics/texture_manager.o: src/graphics/texture_manager.cpp.o

.PHONY : src/graphics/texture_manager.o

# target to build an object file
src/graphics/texture_manager.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/texture_manager.cpp.o
.PHONY : src/graphics/texture_manager.cpp.o

src/graphics/texture_manager.i: src/graphics/texture_manager.cpp.i

.PHONY : src/graphics/texture_manager.i

# target to preprocess a source file
src/graphics/texture_manager.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/texture_manager.cpp.i
.PHONY : src/graphics/texture_manager.cpp.i

src/graphics/texture_manager.s: src/graphics/texture_manager.cpp.s

.PHONY : src/graphics/texture_manager.s

# target to generate assembly for a file
src/graphics/texture_manager.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/graphics/texture_manager.cpp.s
.PHONY : src/graphics/texture_manager.cpp.s

src/input/input_manager.o: src/input/input_manager.cpp.o

.PHONY : src/input/input_manager.o

# target to build an object file
src/input/input_manager.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/input/input_manager.cpp.o
.PHONY : src/input/input_manager.cpp.o

src/input/input_manager.i: src/input/input_manager.cpp.i

.PHONY : src/input/input_manager.i

# target to preprocess a source file
src/input/input_manager.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/input/input_manager.cpp.i
.PHONY : src/input/input_manager.cpp.i

src/input/input_manager.s: src/input/input_manager.cpp.s

.PHONY : src/input/input_manager.s

# target to generate assembly for a file
src/input/input_manager.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/input/input_manager.cpp.s
.PHONY : src/input/input_manager.cpp.s

src/input/mouse.o: src/input/mouse.cpp.o

.PHONY : src/input/mouse.o

# target to build an object file
src/input/mouse.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/input/mouse.cpp.o
.PHONY : src/input/mouse.cpp.o

src/input/mouse.i: src/input/mouse.cpp.i

.PHONY : src/input/mouse.i

# target to preprocess a source file
src/input/mouse.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/input/mouse.cpp.i
.PHONY : src/input/mouse.cpp.i

src/input/mouse.s: src/input/mouse.cpp.s

.PHONY : src/input/mouse.s

# target to generate assembly for a file
src/input/mouse.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/input/mouse.cpp.s
.PHONY : src/input/mouse.cpp.s

src/utility.o: src/utility.cpp.o

.PHONY : src/utility.o

# target to build an object file
src/utility.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/utility.cpp.o
.PHONY : src/utility.cpp.o

src/utility.i: src/utility.cpp.i

.PHONY : src/utility.i

# target to preprocess a source file
src/utility.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/utility.cpp.i
.PHONY : src/utility.cpp.i

src/utility.s: src/utility.cpp.s

.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/utility.cpp.s
.PHONY : src/utility.cpp.s

src/widgets/button.o: src/widgets/button.cpp.o

.PHONY : src/widgets/button.o

# target to build an object file
src/widgets/button.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/widgets/button.cpp.o
.PHONY : src/widgets/button.cpp.o

src/widgets/button.i: src/widgets/button.cpp.i

.PHONY : src/widgets/button.i

# target to preprocess a source file
src/widgets/button.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/widgets/button.cpp.i
.PHONY : src/widgets/button.cpp.i

src/widgets/button.s: src/widgets/button.cpp.s

.PHONY : src/widgets/button.s

# target to generate assembly for a file
src/widgets/button.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/widgets/button.cpp.s
.PHONY : src/widgets/button.cpp.s

src/widgets/label.o: src/widgets/label.cpp.o

.PHONY : src/widgets/label.o

# target to build an object file
src/widgets/label.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/widgets/label.cpp.o
.PHONY : src/widgets/label.cpp.o

src/widgets/label.i: src/widgets/label.cpp.i

.PHONY : src/widgets/label.i

# target to preprocess a source file
src/widgets/label.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/widgets/label.cpp.i
.PHONY : src/widgets/label.cpp.i

src/widgets/label.s: src/widgets/label.cpp.s

.PHONY : src/widgets/label.s

# target to generate assembly for a file
src/widgets/label.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/src/widgets/label.cpp.s
.PHONY : src/widgets/label.cpp.s

tests/engine/state_machine.unit.o: tests/engine/state_machine.unit.cpp.o

.PHONY : tests/engine/state_machine.unit.o

# target to build an object file
tests/engine/state_machine.unit.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/state_machine_test.dir/build.make dependencies/yage/CMakeFiles/state_machine_test.dir/tests/engine/state_machine.unit.cpp.o
.PHONY : tests/engine/state_machine.unit.cpp.o

tests/engine/state_machine.unit.i: tests/engine/state_machine.unit.cpp.i

.PHONY : tests/engine/state_machine.unit.i

# target to preprocess a source file
tests/engine/state_machine.unit.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/state_machine_test.dir/build.make dependencies/yage/CMakeFiles/state_machine_test.dir/tests/engine/state_machine.unit.cpp.i
.PHONY : tests/engine/state_machine.unit.cpp.i

tests/engine/state_machine.unit.s: tests/engine/state_machine.unit.cpp.s

.PHONY : tests/engine/state_machine.unit.s

# target to generate assembly for a file
tests/engine/state_machine.unit.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/state_machine_test.dir/build.make dependencies/yage/CMakeFiles/state_machine_test.dir/tests/engine/state_machine.unit.cpp.s
.PHONY : tests/engine/state_machine.unit.cpp.s

tests/graphics/graphics_manager.unit.o: tests/graphics/graphics_manager.unit.cpp.o

.PHONY : tests/graphics/graphics_manager.unit.o

# target to build an object file
tests/graphics/graphics_manager.unit.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/tests/graphics/graphics_manager.unit.cpp.o
.PHONY : tests/graphics/graphics_manager.unit.cpp.o

tests/graphics/graphics_manager.unit.i: tests/graphics/graphics_manager.unit.cpp.i

.PHONY : tests/graphics/graphics_manager.unit.i

# target to preprocess a source file
tests/graphics/graphics_manager.unit.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/tests/graphics/graphics_manager.unit.cpp.i
.PHONY : tests/graphics/graphics_manager.unit.cpp.i

tests/graphics/graphics_manager.unit.s: tests/graphics/graphics_manager.unit.cpp.s

.PHONY : tests/graphics/graphics_manager.unit.s

# target to generate assembly for a file
tests/graphics/graphics_manager.unit.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/tests/graphics/graphics_manager.unit.cpp.s
.PHONY : tests/graphics/graphics_manager.unit.cpp.s

tests/graphics/spritesheet.o: tests/graphics/spritesheet.cpp.o

.PHONY : tests/graphics/spritesheet.o

# target to build an object file
tests/graphics/spritesheet.cpp.o:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/tests/graphics/spritesheet.cpp.o
.PHONY : tests/graphics/spritesheet.cpp.o

tests/graphics/spritesheet.i: tests/graphics/spritesheet.cpp.i

.PHONY : tests/graphics/spritesheet.i

# target to preprocess a source file
tests/graphics/spritesheet.cpp.i:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/tests/graphics/spritesheet.cpp.i
.PHONY : tests/graphics/spritesheet.cpp.i

tests/graphics/spritesheet.s: tests/graphics/spritesheet.cpp.s

.PHONY : tests/graphics/spritesheet.s

# target to generate assembly for a file
tests/graphics/spritesheet.cpp.s:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(MAKE) -f dependencies/yage/CMakeFiles/graphics_test.dir/build.make dependencies/yage/CMakeFiles/graphics_test.dir/tests/graphics/spritesheet.cpp.s
.PHONY : tests/graphics/spritesheet.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... state_machine_test"
	@echo "... rebuild_cache"
	@echo "... yage"
	@echo "... all_tests"
	@echo "... graphics_test"
	@echo "... src/engine/game_engine.o"
	@echo "... src/engine/game_engine.i"
	@echo "... src/engine/game_engine.s"
	@echo "... src/engine/game_state.o"
	@echo "... src/engine/game_state.i"
	@echo "... src/engine/game_state.s"
	@echo "... src/engine/state_machine.o"
	@echo "... src/engine/state_machine.i"
	@echo "... src/engine/state_machine.s"
	@echo "... src/engine/states/splash_screen.o"
	@echo "... src/engine/states/splash_screen.i"
	@echo "... src/engine/states/splash_screen.s"
	@echo "... src/events/event_manager.o"
	@echo "... src/events/event_manager.i"
	@echo "... src/events/event_manager.s"
	@echo "... src/graphics/drawable.abstract.o"
	@echo "... src/graphics/drawable.abstract.i"
	@echo "... src/graphics/drawable.abstract.s"
	@echo "... src/graphics/font.o"
	@echo "... src/graphics/font.i"
	@echo "... src/graphics/font.s"
	@echo "... src/graphics/font_manager.o"
	@echo "... src/graphics/font_manager.i"
	@echo "... src/graphics/font_manager.s"
	@echo "... src/graphics/graphics_manager.o"
	@echo "... src/graphics/graphics_manager.i"
	@echo "... src/graphics/graphics_manager.s"
	@echo "... src/graphics/spritesheet.o"
	@echo "... src/graphics/spritesheet.i"
	@echo "... src/graphics/spritesheet.s"
	@echo "... src/graphics/texture.o"
	@echo "... src/graphics/texture.i"
	@echo "... src/graphics/texture.s"
	@echo "... src/graphics/texture_manager.o"
	@echo "... src/graphics/texture_manager.i"
	@echo "... src/graphics/texture_manager.s"
	@echo "... src/input/input_manager.o"
	@echo "... src/input/input_manager.i"
	@echo "... src/input/input_manager.s"
	@echo "... src/input/mouse.o"
	@echo "... src/input/mouse.i"
	@echo "... src/input/mouse.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
	@echo "... src/widgets/button.o"
	@echo "... src/widgets/button.i"
	@echo "... src/widgets/button.s"
	@echo "... src/widgets/label.o"
	@echo "... src/widgets/label.i"
	@echo "... src/widgets/label.s"
	@echo "... tests/engine/state_machine.unit.o"
	@echo "... tests/engine/state_machine.unit.i"
	@echo "... tests/engine/state_machine.unit.s"
	@echo "... tests/graphics/graphics_manager.unit.o"
	@echo "... tests/graphics/graphics_manager.unit.i"
	@echo "... tests/graphics/graphics_manager.unit.s"
	@echo "... tests/graphics/spritesheet.o"
	@echo "... tests/graphics/spritesheet.i"
	@echo "... tests/graphics/spritesheet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/fmmarques/Documentos/Projects/bejeweled && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

