# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.15.2/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.15.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fmmarques/Documentos/Projects/yage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fmmarques/Documentos/Projects/yage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.15.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/cmake-3.15.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/cmake-3.15.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmmarques/Documentos/Projects/yage/CMakeFiles /home/fmmarques/Documentos/Projects/yage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmmarques/Documentos/Projects/yage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics_manager_test

# Build rule for target.
graphics_manager_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_manager_test
.PHONY : graphics_manager_test

# fast build rule for target.
graphics_manager_test/fast:
	$(MAKE) -f CMakeFiles/graphics_manager_test.dir/build.make CMakeFiles/graphics_manager_test.dir/build
.PHONY : graphics_manager_test/fast

#=============================================================================
# Target rules for targets named yage

# Build rule for target.
yage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yage
.PHONY : yage

# fast build rule for target.
yage/fast:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/build
.PHONY : yage/fast

#=============================================================================
# Target rules for targets named state_machine_test

# Build rule for target.
state_machine_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 state_machine_test
.PHONY : state_machine_test

# fast build rule for target.
state_machine_test/fast:
	$(MAKE) -f CMakeFiles/state_machine_test.dir/build.make CMakeFiles/state_machine_test.dir/build
.PHONY : state_machine_test/fast

#=============================================================================
# Target rules for targets named all_tests

# Build rule for target.
all_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_tests
.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	$(MAKE) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f dependencies/googletest/googletest/CMakeFiles/gtest.dir/build.make dependencies/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f dependencies/googletest/googletest/CMakeFiles/gtest_main.dir/build.make dependencies/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/engine/game_engine.o: src/engine/game_engine.cpp.o

.PHONY : src/engine/game_engine.o

# target to build an object file
src/engine/game_engine.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/game_engine.cpp.o
.PHONY : src/engine/game_engine.cpp.o

src/engine/game_engine.i: src/engine/game_engine.cpp.i

.PHONY : src/engine/game_engine.i

# target to preprocess a source file
src/engine/game_engine.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/game_engine.cpp.i
.PHONY : src/engine/game_engine.cpp.i

src/engine/game_engine.s: src/engine/game_engine.cpp.s

.PHONY : src/engine/game_engine.s

# target to generate assembly for a file
src/engine/game_engine.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/game_engine.cpp.s
.PHONY : src/engine/game_engine.cpp.s

src/engine/game_state.o: src/engine/game_state.cpp.o

.PHONY : src/engine/game_state.o

# target to build an object file
src/engine/game_state.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/game_state.cpp.o
.PHONY : src/engine/game_state.cpp.o

src/engine/game_state.i: src/engine/game_state.cpp.i

.PHONY : src/engine/game_state.i

# target to preprocess a source file
src/engine/game_state.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/game_state.cpp.i
.PHONY : src/engine/game_state.cpp.i

src/engine/game_state.s: src/engine/game_state.cpp.s

.PHONY : src/engine/game_state.s

# target to generate assembly for a file
src/engine/game_state.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/game_state.cpp.s
.PHONY : src/engine/game_state.cpp.s

src/engine/state_machine.o: src/engine/state_machine.cpp.o

.PHONY : src/engine/state_machine.o

# target to build an object file
src/engine/state_machine.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/state_machine.cpp.o
.PHONY : src/engine/state_machine.cpp.o

src/engine/state_machine.i: src/engine/state_machine.cpp.i

.PHONY : src/engine/state_machine.i

# target to preprocess a source file
src/engine/state_machine.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/state_machine.cpp.i
.PHONY : src/engine/state_machine.cpp.i

src/engine/state_machine.s: src/engine/state_machine.cpp.s

.PHONY : src/engine/state_machine.s

# target to generate assembly for a file
src/engine/state_machine.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/state_machine.cpp.s
.PHONY : src/engine/state_machine.cpp.s

src/engine/states/splash_screen.o: src/engine/states/splash_screen.cpp.o

.PHONY : src/engine/states/splash_screen.o

# target to build an object file
src/engine/states/splash_screen.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/states/splash_screen.cpp.o
.PHONY : src/engine/states/splash_screen.cpp.o

src/engine/states/splash_screen.i: src/engine/states/splash_screen.cpp.i

.PHONY : src/engine/states/splash_screen.i

# target to preprocess a source file
src/engine/states/splash_screen.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/states/splash_screen.cpp.i
.PHONY : src/engine/states/splash_screen.cpp.i

src/engine/states/splash_screen.s: src/engine/states/splash_screen.cpp.s

.PHONY : src/engine/states/splash_screen.s

# target to generate assembly for a file
src/engine/states/splash_screen.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/engine/states/splash_screen.cpp.s
.PHONY : src/engine/states/splash_screen.cpp.s

src/events/event_manager.o: src/events/event_manager.cpp.o

.PHONY : src/events/event_manager.o

# target to build an object file
src/events/event_manager.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/events/event_manager.cpp.o
.PHONY : src/events/event_manager.cpp.o

src/events/event_manager.i: src/events/event_manager.cpp.i

.PHONY : src/events/event_manager.i

# target to preprocess a source file
src/events/event_manager.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/events/event_manager.cpp.i
.PHONY : src/events/event_manager.cpp.i

src/events/event_manager.s: src/events/event_manager.cpp.s

.PHONY : src/events/event_manager.s

# target to generate assembly for a file
src/events/event_manager.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/events/event_manager.cpp.s
.PHONY : src/events/event_manager.cpp.s

src/graphics/drawable.abstract.o: src/graphics/drawable.abstract.cpp.o

.PHONY : src/graphics/drawable.abstract.o

# target to build an object file
src/graphics/drawable.abstract.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/drawable.abstract.cpp.o
.PHONY : src/graphics/drawable.abstract.cpp.o

src/graphics/drawable.abstract.i: src/graphics/drawable.abstract.cpp.i

.PHONY : src/graphics/drawable.abstract.i

# target to preprocess a source file
src/graphics/drawable.abstract.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/drawable.abstract.cpp.i
.PHONY : src/graphics/drawable.abstract.cpp.i

src/graphics/drawable.abstract.s: src/graphics/drawable.abstract.cpp.s

.PHONY : src/graphics/drawable.abstract.s

# target to generate assembly for a file
src/graphics/drawable.abstract.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/drawable.abstract.cpp.s
.PHONY : src/graphics/drawable.abstract.cpp.s

src/graphics/graphics_manager.o: src/graphics/graphics_manager.cpp.o

.PHONY : src/graphics/graphics_manager.o

# target to build an object file
src/graphics/graphics_manager.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/graphics_manager.cpp.o
.PHONY : src/graphics/graphics_manager.cpp.o

src/graphics/graphics_manager.i: src/graphics/graphics_manager.cpp.i

.PHONY : src/graphics/graphics_manager.i

# target to preprocess a source file
src/graphics/graphics_manager.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/graphics_manager.cpp.i
.PHONY : src/graphics/graphics_manager.cpp.i

src/graphics/graphics_manager.s: src/graphics/graphics_manager.cpp.s

.PHONY : src/graphics/graphics_manager.s

# target to generate assembly for a file
src/graphics/graphics_manager.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/graphics_manager.cpp.s
.PHONY : src/graphics/graphics_manager.cpp.s

src/graphics/texture.o: src/graphics/texture.cpp.o

.PHONY : src/graphics/texture.o

# target to build an object file
src/graphics/texture.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.cpp.o

src/graphics/texture.i: src/graphics/texture.cpp.i

.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.cpp.i

src/graphics/texture.s: src/graphics/texture.cpp.s

.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.cpp.s

src/graphics/texture_manager.o: src/graphics/texture_manager.cpp.o

.PHONY : src/graphics/texture_manager.o

# target to build an object file
src/graphics/texture_manager.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/texture_manager.cpp.o
.PHONY : src/graphics/texture_manager.cpp.o

src/graphics/texture_manager.i: src/graphics/texture_manager.cpp.i

.PHONY : src/graphics/texture_manager.i

# target to preprocess a source file
src/graphics/texture_manager.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/texture_manager.cpp.i
.PHONY : src/graphics/texture_manager.cpp.i

src/graphics/texture_manager.s: src/graphics/texture_manager.cpp.s

.PHONY : src/graphics/texture_manager.s

# target to generate assembly for a file
src/graphics/texture_manager.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/graphics/texture_manager.cpp.s
.PHONY : src/graphics/texture_manager.cpp.s

src/input/input_manager.o: src/input/input_manager.cpp.o

.PHONY : src/input/input_manager.o

# target to build an object file
src/input/input_manager.cpp.o:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/input/input_manager.cpp.o
.PHONY : src/input/input_manager.cpp.o

src/input/input_manager.i: src/input/input_manager.cpp.i

.PHONY : src/input/input_manager.i

# target to preprocess a source file
src/input/input_manager.cpp.i:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/input/input_manager.cpp.i
.PHONY : src/input/input_manager.cpp.i

src/input/input_manager.s: src/input/input_manager.cpp.s

.PHONY : src/input/input_manager.s

# target to generate assembly for a file
src/input/input_manager.cpp.s:
	$(MAKE) -f CMakeFiles/yage.dir/build.make CMakeFiles/yage.dir/src/input/input_manager.cpp.s
.PHONY : src/input/input_manager.cpp.s

tests/engine/state_machine.unit.o: tests/engine/state_machine.unit.cpp.o

.PHONY : tests/engine/state_machine.unit.o

# target to build an object file
tests/engine/state_machine.unit.cpp.o:
	$(MAKE) -f CMakeFiles/state_machine_test.dir/build.make CMakeFiles/state_machine_test.dir/tests/engine/state_machine.unit.cpp.o
.PHONY : tests/engine/state_machine.unit.cpp.o

tests/engine/state_machine.unit.i: tests/engine/state_machine.unit.cpp.i

.PHONY : tests/engine/state_machine.unit.i

# target to preprocess a source file
tests/engine/state_machine.unit.cpp.i:
	$(MAKE) -f CMakeFiles/state_machine_test.dir/build.make CMakeFiles/state_machine_test.dir/tests/engine/state_machine.unit.cpp.i
.PHONY : tests/engine/state_machine.unit.cpp.i

tests/engine/state_machine.unit.s: tests/engine/state_machine.unit.cpp.s

.PHONY : tests/engine/state_machine.unit.s

# target to generate assembly for a file
tests/engine/state_machine.unit.cpp.s:
	$(MAKE) -f CMakeFiles/state_machine_test.dir/build.make CMakeFiles/state_machine_test.dir/tests/engine/state_machine.unit.cpp.s
.PHONY : tests/engine/state_machine.unit.cpp.s

tests/graphics/graphics_manager.unit.o: tests/graphics/graphics_manager.unit.cpp.o

.PHONY : tests/graphics/graphics_manager.unit.o

# target to build an object file
tests/graphics/graphics_manager.unit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_manager_test.dir/build.make CMakeFiles/graphics_manager_test.dir/tests/graphics/graphics_manager.unit.cpp.o
.PHONY : tests/graphics/graphics_manager.unit.cpp.o

tests/graphics/graphics_manager.unit.i: tests/graphics/graphics_manager.unit.cpp.i

.PHONY : tests/graphics/graphics_manager.unit.i

# target to preprocess a source file
tests/graphics/graphics_manager.unit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_manager_test.dir/build.make CMakeFiles/graphics_manager_test.dir/tests/graphics/graphics_manager.unit.cpp.i
.PHONY : tests/graphics/graphics_manager.unit.cpp.i

tests/graphics/graphics_manager.unit.s: tests/graphics/graphics_manager.unit.cpp.s

.PHONY : tests/graphics/graphics_manager.unit.s

# target to generate assembly for a file
tests/graphics/graphics_manager.unit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_manager_test.dir/build.make CMakeFiles/graphics_manager_test.dir/tests/graphics/graphics_manager.unit.cpp.s
.PHONY : tests/graphics/graphics_manager.unit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... graphics_manager_test"
	@echo "... yage"
	@echo "... state_machine_test"
	@echo "... edit_cache"
	@echo "... all_tests"
	@echo "... test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/engine/game_engine.o"
	@echo "... src/engine/game_engine.i"
	@echo "... src/engine/game_engine.s"
	@echo "... src/engine/game_state.o"
	@echo "... src/engine/game_state.i"
	@echo "... src/engine/game_state.s"
	@echo "... src/engine/state_machine.o"
	@echo "... src/engine/state_machine.i"
	@echo "... src/engine/state_machine.s"
	@echo "... src/engine/states/splash_screen.o"
	@echo "... src/engine/states/splash_screen.i"
	@echo "... src/engine/states/splash_screen.s"
	@echo "... src/events/event_manager.o"
	@echo "... src/events/event_manager.i"
	@echo "... src/events/event_manager.s"
	@echo "... src/graphics/drawable.abstract.o"
	@echo "... src/graphics/drawable.abstract.i"
	@echo "... src/graphics/drawable.abstract.s"
	@echo "... src/graphics/graphics_manager.o"
	@echo "... src/graphics/graphics_manager.i"
	@echo "... src/graphics/graphics_manager.s"
	@echo "... src/graphics/texture.o"
	@echo "... src/graphics/texture.i"
	@echo "... src/graphics/texture.s"
	@echo "... src/graphics/texture_manager.o"
	@echo "... src/graphics/texture_manager.i"
	@echo "... src/graphics/texture_manager.s"
	@echo "... src/input/input_manager.o"
	@echo "... src/input/input_manager.i"
	@echo "... src/input/input_manager.s"
	@echo "... tests/engine/state_machine.unit.o"
	@echo "... tests/engine/state_machine.unit.i"
	@echo "... tests/engine/state_machine.unit.s"
	@echo "... tests/graphics/graphics_manager.unit.o"
	@echo "... tests/graphics/graphics_manager.unit.i"
	@echo "... tests/graphics/graphics_manager.unit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

